version: 1.0.{build}
configuration: Release

install:
  - appveyor DownloadFile https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows-dev.zip
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com/box_CIs_standalone
  - testspace -v

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo build script
  
# to run your custom scripts instead of automatic tests
test_script:
  - set > printenv.txt 
  
after_test:
  - testspace test.xml printenv.txt appveyor